#!/usr/bin/env bash

# LiveCD Creator 3
# Copyright (C) 2012-2014  Kevin Atwood
# 
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2010-2013  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

set -u
source /etc/live-cd/common
source /etc/live-cd/default

__check_fs_dir__
__check_lock__
__check_sources_list__

WARNING_MESSAGE "ONLY THE BARE MINIMUM SET OF PACKAGES WILL BE INSTALLED!"
while true;do
	echo "
	1. Ubuntu
	2. Xubuntu
	3. Lubuntu
	4. Kubuntu"
	echo
	EXTRA_QUESTION_MESSAGE "Which desktop environment do you wish to install?" "1-4"
	read choise
    
    case $choise in
        1) GUI_PACKAGES="xserver-xorg xinit ubuntu-desktop"; break ;;
        2) GUI_PACKAGES="xserver-xorg xinit xubuntu-desktop"; break ;;
        3) GUI_PACKAGES="xserver-xorg xinit lubuntu-desktop"; break ;;
        4) GUI_PACKAGES="xserver-xorg xinit kubuntu-desktop"; break ;;
        *) WARNING_MESSAGE "This is not an option!" ;;
    esac
done

__mount_sys__
__mount_dbus__
__chroot__ apt-get install dbus -f -y
__chroot__ dbus-uuidgen --ensure
__chroot__ apt-get install -y ${GUI_PACKAGES} --no-install-recommends
__umount_sys__
__recursive_umount__