#!/usr/bin/env bash

# LiveCD Creator 3
# Copyright (C) 2012-2016  Kevin Atwood
# 
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2010-2013  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

set -u
source /etc/live-cd/common
source /etc/live-cd/default

__check_fs_dir__
__check_lock__

if [ ! -e "$DEB" ];then
    zenity --warning --title="" --text "Debian package does not exist!"
    exit
fi

case "$DEB" in
    *.deb) cp -f "$DEB" "$WORK_DIR/FileSystem/tmp/temp.deb" ;;
    *) ERROR_MESSAGE "This is not a debian package!" ;;
esac

__allow_local_X_access__
__mount_sys__

(
    __chroot__ dpkg -i /tmp/temp.deb
    __chroot__ apt-get install -f -y
) | zenity --title="" --text="Installing debian package..." --progress --width=350 --pulsate --auto-close &

# get zenity process id
PID_ZENITY=${!}

# get firstly created child process id, which is running all tasks
PID_CHILD=$(pgrep -o -P $$)

# loop to check that progress dialog has not been cancelled
while [ "$PID_ZENITY" != "" ]
do
  # get PID of all running tasks
  PID_TASKS=$(pgrep -d ' ' -P ${PID_CHILD})

  # check if zenity PID is still there (dialog box still open)
  PID_ZENITY=$(ps h -o pid --pid ${PID_ZENITY} | xargs)

  # sleep for 2 second
  sleep 2
done

# if some running tasks are still there, kill them
[ "${PID_TASKS}" != "" ] && kill -9 ${PID_TASKS}

__umount_sys__
__recursive_umount__
__block_local_X_access__

## EOF